### ISSUE TITLE
[STYLE CHANGE] Logo on home page is not clearly visible

### ISSUE THREAD

**Issue by Ishita-Ghosh-25** [UBA-GCOEN/StichHub#135]
**Description:**

Once we register, the home page logo is partially visible and it does not match the first page logo

**Reason for Change:**

To improve the user experience

**Current Styling:**

The logo is not visible due to low contrast

**Proposed Styling:**

The logo has to be the same as the first page

**Screenshots or Design Mockups (optional):**
This is how the logo is looking on the home page
<img width="960" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/70560812/bdc6d804-d1ce-4c29-8e92-24ed65eb5184">

While in the first page, the logo is clearly visible
<img width="953" alt="image" src="https://github.com/UBA-GCOEN/StichHub/assets/70560812/758d3f19-dfa9-48a5-8290-d5831b4a112f">

**Additional Information (optional):**

[Provide any additional information that may help in understanding or implementing the style change. This can include any specific requirements or constraints.]

**Priority Level (optional):**

- [x] Low
- [ ] Medium
- [ ] High

**Timeline (optional):**

[Specify any preferred or required timeline for implementing the style change.]

**Possible Implementation Approach (optional):**

[If you have any suggestions or ideas on how the style change could be implemented, feel free to provide them here.]

**Comment by Siddhant-Patil0203** [comment]
Hey @Ishita-Ghosh-25 
The issue here is the logo used on the first page is different, and the logo used on the home page is different,
therefore you just use the same logo used on the first page on the home page as well.

Also, can you change the font color of 'welcome' on home to white current its black?
here you Screenshot of it for your reference:
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/955ee435-2d8e-4351-9ada-6635d5d194d3)

### How it should be ✅
![image](https://github.com/UBA-GCOEN/StichHub/assets/77800620/d2b7ac01-4753-4ca5-a44b-6e49dbfaa0b7)

### So can you do these two changes?
1) Using the same logo used on the first page to the home page
2) Change the font color of text '**Welcome**' on home page

**Comment by Naresh-chandanbatve** [comment]
@Ishita-Ghosh-25

**Comment by Ishita-Ghosh-25** [comment]
@Siddhant-Patil0203 sure. Will do

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 sure. Will do

@Ishita-Ghosh-25 I am assigning you this issue.

**Comment by Ishita-Ghosh-25** [comment]
@Naresh-chandanbatve here is the issue for which I have raised a PR

**Comment by Siddhant-Patil0203** [comment]
> @Naresh-chandanbatve here is the issue for which I have raised a PR

Hey @Ishita-Ghosh-25 , you should refer to your issue no. on the PR you made not on the issue itself. 
this is a good method, which helps maintainers to review your code properly.😄

keep a note of it, and happy coding 👨‍💻
