### ISSUE TITLE
Creating About Us Page

### ISSUE THREAD

**Issue by MohamedMafaz** [UBA-GCOEN/StichHub#140]
Hey Project Admin,
I saw your website and it's simply awesome. I'm a UI/UX Designer and front end developer too. Please assign me thia issue under GSsox'23.

**Comment by Siddhant-Patil0203** [comment]
> Hey Project Admin, I saw your website and it's simply awesome. I'm a UI/UX Designer and front end developer too. Please assign me thia issue under GSsox'23.

Hey @MohamedMafaz
Can you pls elaborate on your issue?

**Comment by Aleesha2002** [comment]
Hello sir, If this Issue is not assigned then I would like to work on this issue...
I can contribute in improving the points as mentioned below:-
1. The images of the contributors here are not aligned
2. Font used for the names can be changed
3. The about us is written in much of upper side which need to be bit in the middle covering the contributors images and the about us description both
4. The description for the about us section and the image attached to it are not well aligned

**Comment by Siddhant-Patil0203** [comment]
hey @Aleesha2002
Can you pls attach the Screenshots for this? 🙂

**Comment by Aleesha2002** [comment]
The about us is written in much of upper side which need to be bit in the middle covering the contributors images and the about us description both
![Screenshot from 2023-06-13 09-04-44](https://github.com/UBA-GCOEN/StichHub/assets/107275325/271c137a-9b46-4e07-a69f-16c0cf6e975a)


![Screenshot from 2023-06-13 09-04-30](https://github.com/UBA-GCOEN/StichHub/assets/107275325/42906868-e3ac-4ec3-bc76-30edd696806e)

The description for the about us section and the image attached to it are not well aligned
![Screenshot from 2023-06-13 09-03-54](https://github.com/UBA-GCOEN/StichHub/assets/107275325/283ed7d0-de1d-4576-8c70-2595cd37fd06)

**Comment by Siddhant-Patil0203** [comment]
@Aleesha2002 We don't need any changes in this as of now, thank you.
