### ISSUE TITLE
BUG: Social icons redirecting to github only

### ISSUE THREAD

**Issue by MisterMickey** [UBA-GCOEN/StichHub#382]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### What happened?

Social icons redirecting to github only

### Add ScreenShots

![Screenshot from 2023-06-23 11-32-31](https://github.com/UBA-GCOEN/StichHub/assets/93720428/929d9f96-f0f4-45b7-9cd5-833be9085122)

### What browser are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Patil0203** [comment]
@MisterMickey 
Go ahead 

Instead of Linkedin add Youtube here :

Gmail: stichhub.office@gmail.com
GitHub : https://github.com/UBA-GCOEN/StichHub
Youtube: https://www.youtube.com/channel/UCjkwYo58eYv6ZGqu4IQiU0w
Twitter : https://twitter.com/StichHub_
Instagram: https://www.instagram.com/stichhub_

Also, Keep the Sequence like this : 

Gmail | Github | Youtube | Twitter | Instagram

**Comment by MisterMickey** [comment]
@Siddhant-Patil0203 All changes done.
